name: 不具合の報告
description: 不具合を報告するためのテンプレートです。脆弱性の報告は、[脆弱性報告ルート](https://example.com)を通じて提出してください。
title: "[Bug]: "
labels: ["不具合", "untriaged"]
projects: ["demo"]
# assignees:
#   - octocat
body:
  - type: markdown
    attributes:
      value: |
        不具合の報告にご協力いただきありがとうございます！
  - type: textarea
    id: expected-behavior
    attributes:
      label: 期待する動作
      description: 本来あるべき状態や動作を詳細に説明してください。
    validations:
      required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: 現在の動作
      description: 現在の状態や動作を説明してください。
    validations:
      required: true
  - type: textarea
    id: possible-solution
    attributes:
      label: 考えられる解決策
      description: どのようにすれば不具合を解決できるか、案を記載してください。不明な場合は未記載で構いません。
  - type: textarea
    id: repro-steps
    attributes:
      label: 再現手順
      description: 不具合の再現手順や入力値を記載してください。再現手順が不明な場合は未記載で構いません。
      value: |
        1.
        2.
        3.
  - type: textarea
    id: environment
    attributes:
      label: 環境
      description: 不具合の発生する環境やバージョンについて、詳細に記述してください。
      value: |
        - OS / バージョン : Windows xx / Linux (distribution) / macOS xx
        - ブラウザー / バージョン : Chrome xx.xx / Edge xx.xx / FireFox xx.xx / Safari xx.xx
        - その他 : ビルド環境などできる限り詳細な情報
  - type: textarea
    id: logs
    attributes:
      label: ログ・スタックトレース
      description: スタックトレースなど、アプリケーションやビルドシステムの出力するログを添付してください。
      render: text
  - type: checkboxes
    id: confirmation
    attributes:
      label: 確認
      description: 以下の項目の確認および同意ができたら、チェックボックスをオンにしてください。
      options:
        - label: 報告しようとしている不具合が脆弱性に関するものではないことを確認しました。脆弱性の場合は [こちら](https://example.com) から報告してください。
          required: true
        - label: 報告しようとしている不具合が [Issue](https://example.com) および [Disucussions](https://example.com) に登録済みではないことを確認しました。
          required: true
        - label: 私たちの [行動規範](https://example.com) に従うことを同意します。
          required: true
